version: '3.8'

services:
  #--- Gateway da API ---
  api_gateway:
    build: ./services/api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./services/api_gateway:/app
    env_file:
      - ./.env
    depends_on:
      - rabbitmq


  #--- Fila de Mensagens ---
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
